version: '3.1'
services:
  nessus:
    image: tenableofficial/nessus
    restart: always
    container_name: nessus
    environment:
      USERNAME: ${NESSUS_USERNAME}
      PASSWORD: ${NESSUS_PASSWORD}
      ACTIVATION_CODE: ${NESSUS_ACTIVATION_CODE}
    ports:
      - 8834:8834