version: '3.1'
secrets:
  nessus_user:
    external: true
  nessus_pwd:
    external: true
  nessus_activation_code:
    external: true
services:
  nessus:
    image: tenableofficial/nessus
    restart: always
    container_name: nessus-scanner
    environment:
      # USERNAME: /run/secrets/nessus_user
      # PASSWORD: /run/secrets/nessus_pwd
      # ACTIVATION_CODE: /run/secrets/nessus_activation_code
    ports:
      - 8834:8836
    volumes: 
      - ./config:/usr/bin/
    secrets:
      - nessus_user
      - nessus_pwd
      - nessus_activation_code