version: '3.1'
services:
  nessus:
    image: tenableofficial/nessus
    restart: always
    container_name: nessus
    environment:
      USERNAME: "ekelly@paraport.com"
      PASSWORD: "104090Emma!!"
      ACTIVATION_CODE: "VUK9-JX4L-ME4B-99GM"
    ports:
      - 8834:8834